In [1]:
import pandas as pd

In [105]:
files = ['./Data/Rolling/ManhattanSalesFinal.csv',
         './Data/Rolling/QueensSalesFinal.csv',
         './Data/Rolling/StatenIslandSalesFinal.csv',
         './Data/Rolling/BrooklynSalesFinal.csv',
         './Data/Rolling/BronxSalesFinal.csv']

In [106]:
ffiles = ['./Data/Rolling/ManhattanSalesFinalFE.csv',
          './Data/Rolling/QueensSalesFinalFE.csv',
          './Data/Rolling/StatenIslandSalesFinalFE.csv',
          './Data/Rolling/BrooklynSalesFinalFE.csv',
          './Data/Rolling/BronxSalesFinalFE.csv']

In [107]:
fileNum = 4

In [108]:
df = pd.read_csv(files[fileNum])

In [109]:
df.head(30)

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,BLOCK,LOT,BUILDING CLASS AT PRESENT,ADDRESS,ZIP CODE,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,bctcb2020
0,BX,BATHGATE,01 ONE FAMILY DWELLINGS,3037,101,S0,443 EAST 180 STREET,10457,1952.0,1,S0,720000,2022-02-23,20395001003
1,BX,BATHGATE,01 ONE FAMILY DWELLINGS,3039,29,A5,2327 WASHINGTON AVE,10458,1910.0,1,A5,499999,2022-04-28,20385002001
2,BX,BATHGATE,01 ONE FAMILY DWELLINGS,3039,63,A1,469 EAST 185 STREET,10458,1910.0,1,A1,599000,2022-05-17,20385002001
3,BX,BATHGATE,01 ONE FAMILY DWELLINGS,3039,63,A1,469 EAST 185TH STREET,10458,1910.0,1,A1,455000,2021-12-23,20385002001
4,BX,BATHGATE,01 ONE FAMILY DWELLINGS,3045,12,A1,2052 BATHGATE AVENUE,10457,1910.0,1,A1,580000,2021-07-22,20395002003
5,BX,BATHGATE,01 ONE FAMILY DWELLINGS,3046,38,A1,2077 BATHGATE AVENUE,10457,1899.0,1,A1,540000,2022-04-19,20395002002
6,BX,BATHGATE,01 ONE FAMILY DWELLINGS,3050,80,A1,2257 BATHGATE AVENUE,10457,1901.0,1,A1,600000,2022-04-28,20385004006
7,BX,BATHGATE,01 ONE FAMILY DWELLINGS,3053,108,A9,2317 BASSFORD AVENUE,10458,1901.0,1,A9,251600,2021-08-17,20385003004
8,BX,BATHGATE,01 ONE FAMILY DWELLINGS,3053,108,A9,2317 BASSFORD AVENUE,10458,1901.0,1,A9,564000,2022-04-06,20385003004
9,BX,BATHGATE,02 TWO FAMILY DWELLINGS,2912,140,B1,3821 3RD AVENUE,10457,1993.0,1,B1,680000,2022-05-31,20169001003
10,BX,BATHGATE,02 TWO FAMILY DWELLINGS,2912,146,B1,3809 3RD AVENUE,10457,1993.0,1,B1,680000,2021-08-11,20169001003
11,BX,BATHGATE,02 TWO FAMILY DWELLINGS,2927,120,B1,"1495 CROTONA PLACE,",10456,1994.0,1,B1,620000,2021-12-16,20169001006
12,BX,BATHGATE,02 TWO FAMILY DWELLINGS,2929,114,B1,3854 3RD AVENUE,10457,1995.0,1,B1,525000,2022-06-09,20167002008
13,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3030,61,B3,4467 PARK AVENUE,10457,1899.0,1,B3,650000,2021-08-23,20383041005
14,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3036,43,B1,2057 WASHINGTON AVE,10457,1997.0,1,B1,100,2022-03-19,20395002000
15,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3036,146,B1,2049 WASHINGTON AVENUE,10457,1997.0,1,B1,540000,2021-11-03,20395002000
16,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3039,18,B3,464 EAST 185 STREET,10458,1910.0,1,B3,669000,2022-06-03,20385002001
17,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3039,158,B1,474 EAST 186 STREET,10458,1997.0,1,B1,695000,2021-09-03,20385002001
18,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3040,16,B2,464 EAST 187 STREET,10458,1910.0,1,B2,820000,2021-12-30,20385001007
19,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3044,159,B1,1992 BATHGATE AVENUE,10457,1998.0,1,B1,725000,2022-04-18,20395003000
20,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3044,165,B1,2004 BATHGATE AVENUE,10457,1998.0,1,B1,789000,2021-11-22,20395003000
21,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3047,9,B9,2122 WASHINGTON AVENUE,10457,1901.0,1,B9,355000,2022-01-05,20395001004
22,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3050,79,B2,2259 BATHGATE AVENUE,10457,1901.0,1,B2,726000,2022-04-28,20385004006
23,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3050,82,B2,2253 BATHGATE AVE,10457,1901.0,1,B2,763000,2022-01-26,20385004006
24,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3050,90,B2,505 E 182 STREET,10457,1901.0,1,B2,734000,2021-07-13,20385004006
25,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3053,16,B2,2303 BATHGATE AVENUE,10458,1901.0,1,B2,460000,2021-12-16,20385003004
26,BX,BATHGATE,02 TWO FAMILY DWELLINGS,3053,17,B2,2301 BATHGATE AVE,10458,1901.0,1,B2,790000,2021-10-08,20385003004
27,BX,BATHGATE,03 THREE FAMILY DWELLINGS,3035,53,C0,459 EAST 178TH ST,10457,2007.0,1,C0,670000,2021-07-26,20395003001
28,BX,BATHGATE,03 THREE FAMILY DWELLINGS,3039,13,C0,456 EAST 185 STREET,10458,1910.0,1,C0,690000,2021-08-30,20385002001
29,BX,BATHGATE,03 THREE FAMILY DWELLINGS,3040,13,C0,458 EAST 187 STREET,10458,1910.0,1,C0,852000,2021-12-06,20385001007

In [110]:
df['h3geo'] = 0

In [111]:
df['YEAR BUILT'].describe()

count    5496.000000
mean     1945.899927
std        27.371541
min      1868.000000
25%      1925.000000
50%      1946.000000
75%      1960.000000
max      2021.000000
Name: YEAR BUILT, dtype: float64

In [112]:
for i in range(1800, 2030, 10):
    df['{:4.0f}s'.format(i)] = 0

for index, row in df.iterrows():
    col = row['YEAR BUILT'] - (row['YEAR BUILT'] % 10)
    df.iloc[index, df.columns.get_loc('{:4.0f}s'.format(col))] = 1

In [113]:
df = pd.get_dummies(df, prefix=['BUILDING CLASS CATEGORY', 'BUILDING CLASS', 'TAX CLASS'],
                    columns=['BUILDING CLASS CATEGORY', 'BUILDING CLASS AT PRESENT', 'TAX CLASS AT TIME OF SALE'])

In [114]:
df.to_csv(ffiles[fileNum], index=False)

In [24]:
sales_df = pd.read_csv('../../data/clean/SalesFinal.csv')

sales_df

,BOROUGH,NEIGHBORHOOD,BLOCK,LOT,ADDRESS,ZIP CODE,YEAR BUILT,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,...,BUILDING CLASS_Z7,BUILDING CLASS_12 CONDOS - WALKUP APARTMENTS,BUILDING CLASS_G5,BUILDING CLASS_HR,BUILDING CLASS_I2,BUILDING CLASS_Q9,BUILDING CLASS_R7,BUILDING CLASS_W3,BUILDING CLASS_P8,BUILDING CLASS_Z3
0,MN,ALPHABET CITY,377,70,235 EAST 7TH STREET,10009.0,2003.0,B1,3025000,2021-12-16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,MN,ALPHABET CITY,389,45,631 EAST 6TH STREET,10009.0,1900.0,C4,5250000,2022-06-16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,MN,ALPHABET CITY,389,47,627 EAST 6TH STREET,10009.0,1910.0,C4,5650000,2022-03-30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,MN,ALPHABET CITY,390,50,"209 EAST 7 STREET, 5W",10009.0,1900.0,C1,235251,2022-06-22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,MN,ALPHABET CITY,390,57,197 EAST 7TH STREET,10009.0,1910.0,C7,10,2022-01-13,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73232,BX,WOODLAWN,3376,58,4277 KATONAH AVENUE,10470.0,1930.0,S4,800000,2022-01-19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73233,BX,WOODLAWN,3377,59,4299 KATONAH AVENUE,10470.0,1931.0,K4,4100000,2021-12-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73234,BX,WOODLAWN,3374,1,235 EAST 233RD STREET,10470.0,1931.0,G1,930000,2021-12-10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73235,BX,WOODLAWN,3395,63,4219 WEBSTER AVENUE,10470.0,1931.0,G1,3000000,2021-12-17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73236,BX,WOODLAWN,3395,44,4221 PETERS PLACE,10470.0,1931.0,E1,120000,2021-07-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
sales_df['hex_id'] = sales_df['h3geo']
h3df = pd.read_json('../../data/clean/bbl_to_h3.json', orient='index', convert_axes=False)

print(h3df)


def geth3(borough):
    if borough == 'MN':
        bbl = '1'
    elif borough == 'BX':
        bbl = '2'
    elif borough == 'BK':
        bbl = '3'
    elif borough == 'QN':
        bbl = '4'
    elif borough == 'SI':
        bbl = '5'

    return bbl
    # else:
    #     return 'BOROUGH FAIL'
    # bbl = bbl + f"{block:05d}{lot:04d}"
    # try:
    #     return h3df.loc[[bbl]]['h3_10'][0]
    # except:
    #     return float('NaN')


sales_df['bbl'] = sales_df['BOROUGH'].apply(geth3)
sales_df['bbl'] = sales_df['bbl'] + sales_df['BLOCK'].apply(lambda x: f"{x:05d}") + sales_df['LOT'].apply(
    lambda x: f"{x:04d}")

# fmdf = sales_df[sales_df['hex_id'] == "0"]
adf = sales_df[sales_df['hex_id'] != "0"]

# fmdf['hex_id'] = fmdf['bbl'].apply(lambda x: h3df.loc[['bbl']]['h3_10'][0])

# end_df = pd.concat([adf, fmdf])

                      h3_10
1000010010  8a2a1072b867fff
1000020001  8a2a1072804ffff
1000020002  8a2a10728337fff
1000020023  8a2a10728a87fff
1000030001  8a2a1072800ffff
...                     ...
5080500083  8a2a106e60dffff
5080500086  8a2a106e60dffff
5080500089  8a2a106e60dffff
5080500092  8a2a106e6767fff
5080500094  8a2a106e6767fff

[834973 rows x 1 columns]

In [72]:
# end_df.groupby('hex_id').agg({'SALE PRICE': 'sum'})
# adf.groupby('hex_id').agg({'SALE PRICE': 'sum'})

# adf.groupby('hex_id').agg({'SALE PRICE': 'sum'})
out = adf.groupby('hex_id').agg('sum')

In [73]:
out = adf[['hex_id', 'SALE PRICE', '1800s',
           '1810s',
           '1820s',
           '1830s',
           '1840s',
           '1850s',
           '1860s',
           '1870s',
           '1880s',
           '1890s',
           '1900s',
           '1910s',
           '1920s',
           '1930s',
           '1940s',
           '1950s',
           '1960s',
           '1970s',
           '1980s',
           '1990s',
           '2000s',
           '2010s',
           '2020s',
           'BUILDING CLASS CATEGORY_01 ONE FAMILY DWELLINGS',
           'BUILDING CLASS CATEGORY_02 TWO FAMILY DWELLINGS',
           'BUILDING CLASS CATEGORY_03 THREE FAMILY DWELLINGS',
           'BUILDING CLASS CATEGORY_04 TAX CLASS 1 CONDOS',
           'BUILDING CLASS CATEGORY_07 RENTALS - WALKUP APARTMENTS',
           'BUILDING CLASS CATEGORY_08 RENTALS - ELEVATOR APARTMENTS',
           'BUILDING CLASS CATEGORY_09 COOPS - WALKUP APARTMENTS',
           'BUILDING CLASS CATEGORY_10 COOPS - ELEVATOR APARTMENTS',
           'BUILDING CLASS CATEGORY_11 SPECIAL CONDO BILLING LOTS',
           'BUILDING CLASS CATEGORY_12 CONDOS - WALKUP APARTMENTS',
           'BUILDING CLASS CATEGORY_13 CONDOS - ELEVATOR APARTMENTS',
           'BUILDING CLASS CATEGORY_14 RENTALS - 4-10 UNIT',
           'BUILDING CLASS CATEGORY_15 CONDOS - 2-10 UNIT RESIDENTIAL',
           'BUILDING CLASS CATEGORY_16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT',
           'BUILDING CLASS CATEGORY_17 CONDO COOPS',
           'BUILDING CLASS CATEGORY_21 OFFICE BUILDINGS',
           'BUILDING CLASS CATEGORY_22 STORE BUILDINGS',
           'BUILDING CLASS CATEGORY_25 LUXURY HOTELS',
           'BUILDING CLASS CATEGORY_26 OTHER HOTELS',
           'BUILDING CLASS CATEGORY_27 FACTORIES',
           'BUILDING CLASS CATEGORY_28 COMMERCIAL CONDOS',
           'BUILDING CLASS CATEGORY_29 COMMERCIAL GARAGES',
           'BUILDING CLASS CATEGORY_30 WAREHOUSES',
           'BUILDING CLASS CATEGORY_31 COMMERCIAL VACANT LAND',
           'BUILDING CLASS CATEGORY_32 HOSPITAL AND HEALTH FACILITIES',
           'BUILDING CLASS CATEGORY_33 EDUCATIONAL FACILITIES',
           'BUILDING CLASS CATEGORY_34 THEATRES',
           'BUILDING CLASS CATEGORY_35 INDOOR PUBLIC AND CULTURAL FACILITIES',
           'BUILDING CLASS CATEGORY_36 OUTDOOR RECREATIONAL FACILITIES',
           'BUILDING CLASS CATEGORY_37 RELIGIOUS FACILITIES',
           'BUILDING CLASS CATEGORY_38 ASYLUMS AND HOMES',
           'BUILDING CLASS CATEGORY_39 TRANSPORTATION FACILITIES',
           'BUILDING CLASS CATEGORY_40 SELECTED GOVERNMENTAL FACILITIES',
           'BUILDING CLASS CATEGORY_41 TAX CLASS 4 - OTHER',
           'BUILDING CLASS CATEGORY_42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC',
           'BUILDING CLASS CATEGORY_43 CONDO OFFICE BUILDINGS',
           'BUILDING CLASS CATEGORY_44 CONDO PARKING',
           'BUILDING CLASS CATEGORY_45 CONDO HOTELS',
           'BUILDING CLASS CATEGORY_46 CONDO STORE BUILDINGS',
           'BUILDING CLASS CATEGORY_47 CONDO NON-BUSINESS STORAGE',
           'BUILDING CLASS CATEGORY_48 CONDO TERRACES/GARDENS/CABANAS',
           'BUILDING CLASS CATEGORY_49 CONDO WAREHOUSES/FACTORY/INDUS',
           'BUILDING CLASS_13 CONDOS - ELEVATOR APARTMENTS',
           'BUILDING CLASS_15 CONDOS - 2-10 UNIT RESIDENTIAL',
           'BUILDING CLASS_17 CONDO COOPS',
           'BUILDING CLASS_44 CONDO PARKING',
           'BUILDING CLASS_A1',
           'BUILDING CLASS_A4',
           'BUILDING CLASS_A5',
           'BUILDING CLASS_A7',
           'BUILDING CLASS_A9',
           'BUILDING CLASS_B1',
           'BUILDING CLASS_B2',
           'BUILDING CLASS_B3',
           'BUILDING CLASS_B9',
           'BUILDING CLASS_C0',
           'BUILDING CLASS_C1',
           'BUILDING CLASS_C2',
           'BUILDING CLASS_C3',
           'BUILDING CLASS_C4',
           'BUILDING CLASS_C5',
           'BUILDING CLASS_C6',
           'BUILDING CLASS_C7',
           'BUILDING CLASS_C8',
           'BUILDING CLASS_C9',
           'BUILDING CLASS_D0',
           'BUILDING CLASS_D1',
           'BUILDING CLASS_D2',
           'BUILDING CLASS_D3',
           'BUILDING CLASS_D4',
           'BUILDING CLASS_D5',
           'BUILDING CLASS_D6',
           'BUILDING CLASS_D7',
           'BUILDING CLASS_D8',
           'BUILDING CLASS_D9',
           'BUILDING CLASS_E1',
           'BUILDING CLASS_E2',
           'BUILDING CLASS_E7',
           'BUILDING CLASS_E9',
           'BUILDING CLASS_F5',
           'BUILDING CLASS_G1',
           'BUILDING CLASS_G2',
           'BUILDING CLASS_G3',
           'BUILDING CLASS_G6',
           'BUILDING CLASS_G7',
           'BUILDING CLASS_G9',
           'BUILDING CLASS_GW',
           'BUILDING CLASS_H1',
           'BUILDING CLASS_H2',
           'BUILDING CLASS_H3',
           'BUILDING CLASS_H6',
           'BUILDING CLASS_H7',
           'BUILDING CLASS_H8',
           'BUILDING CLASS_H9',
           'BUILDING CLASS_HB',
           'BUILDING CLASS_HS',
           'BUILDING CLASS_I1',
           'BUILDING CLASS_I5',
           'BUILDING CLASS_I7',
           'BUILDING CLASS_I9',
           'BUILDING CLASS_J6',
           'BUILDING CLASS_J8',
           'BUILDING CLASS_K1',
           'BUILDING CLASS_K2',
           'BUILDING CLASS_K4',
           'BUILDING CLASS_K7',
           'BUILDING CLASS_K9',
           'BUILDING CLASS_M1',
           'BUILDING CLASS_M2',
           'BUILDING CLASS_M3',
           'BUILDING CLASS_N2',
           'BUILDING CLASS_O2',
           'BUILDING CLASS_O3',
           'BUILDING CLASS_O4',
           'BUILDING CLASS_O5',
           'BUILDING CLASS_O6',
           'BUILDING CLASS_O7',
           'BUILDING CLASS_O8',
           'BUILDING CLASS_O9',
           'BUILDING CLASS_P2',
           'BUILDING CLASS_P9',
           'BUILDING CLASS_Q1',
           'BUILDING CLASS_R1',
           'BUILDING CLASS_R2',
           'BUILDING CLASS_R3',
           'BUILDING CLASS_R4',
           'BUILDING CLASS_R5',
           'BUILDING CLASS_R6',
           'BUILDING CLASS_R8',
           'BUILDING CLASS_R9',
           'BUILDING CLASS_RA',
           'BUILDING CLASS_RB',
           'BUILDING CLASS_RG',
           'BUILDING CLASS_RH',
           'BUILDING CLASS_RK',
           'BUILDING CLASS_RP',
           'BUILDING CLASS_RR',
           'BUILDING CLASS_RS',
           'BUILDING CLASS_RT',
           'BUILDING CLASS_RW',
           'BUILDING CLASS_S0',
           'BUILDING CLASS_S1',
           'BUILDING CLASS_S2',
           'BUILDING CLASS_S3',
           'BUILDING CLASS_S4',
           'BUILDING CLASS_S5',
           'BUILDING CLASS_S9',
           'BUILDING CLASS_T9',
           'BUILDING CLASS_V1',
           'BUILDING CLASS_W1',
           'BUILDING CLASS_W2',
           'BUILDING CLASS_W6',
           'BUILDING CLASS_W9',
           'BUILDING CLASS_Y8',
           'BUILDING CLASS_Z5',
           'BUILDING CLASS_Z9',
           'TAX CLASS_1',
           'TAX CLASS_2',
           'TAX CLASS_4',
           'BUILDING CLASS CATEGORY_05 TAX CLASS 1 VACANT LAND',
           'BUILDING CLASS CATEGORY_06 TAX CLASS 1 - OTHER',
           'BUILDING CLASS_04 TAX CLASS 1 CONDOS',
           'BUILDING CLASS_11 SPECIAL CONDO BILLING LOTS',
           'BUILDING CLASS_47 CONDO NON-BUSINESS STORAGE',
           'BUILDING CLASS_A0',
           'BUILDING CLASS_A2',
           'BUILDING CLASS_A3',
           'BUILDING CLASS_A6',
           'BUILDING CLASS_A8',
           'BUILDING CLASS_F1',
           'BUILDING CLASS_F2',
           'BUILDING CLASS_F4',
           'BUILDING CLASS_F9',
           'BUILDING CLASS_G0',
           'BUILDING CLASS_G4',
           'BUILDING CLASS_G8',
           'BUILDING CLASS_GU',
           'BUILDING CLASS_I6',
           'BUILDING CLASS_K3',
           'BUILDING CLASS_K5',
           'BUILDING CLASS_K8',
           'BUILDING CLASS_M4',
           'BUILDING CLASS_M9',
           'BUILDING CLASS_N9',
           'BUILDING CLASS_O1',
           'BUILDING CLASS_P5',
           'BUILDING CLASS_P6',
           'BUILDING CLASS_Q8',
           'BUILDING CLASS_V0',
           'BUILDING CLASS_V2',
           'BUILDING CLASS_V3',
           'BUILDING CLASS_V6',
           'BUILDING CLASS_V9',
           'BUILDING CLASS_W4',
           'BUILDING CLASS_W8',
           'BUILDING CLASS_Y3',
           'BUILDING CLASS_Z0',
           'BUILDING CLASS_08 RENTALS - ELEVATOR APARTMENTS',
           'BUILDING CLASS_K6',
           'BUILDING CLASS_Z7',
           'BUILDING CLASS_12 CONDOS - WALKUP APARTMENTS',
           'BUILDING CLASS_G5',
           'BUILDING CLASS_HR',
           'BUILDING CLASS_I2',
           'BUILDING CLASS_Q9',
           'BUILDING CLASS_R7',
           'BUILDING CLASS_W3',
           'BUILDING CLASS_P8',
           'BUILDING CLASS_Z3'
           ]]

In [78]:
from sklearn.preprocessing import PCA

ImportError: cannot import name 'PCA' from 'sklearn.preprocessing' (/home/thowe/anaconda3/envs/plz-gpu/lib/python3.8/site-packages/sklearn/preprocessing/__init__.py)

In [76]:
out.to_csv('../../data/clean/sale_by_hex.csv')